name: copy_with_extension_gen
version: 5.0.3
description: Automatically generating `copyWith` extensions code for classes with `@CopyWith()` annotation.
repository: https://github.com/numen31337/copy_with_extension
homepage: https://github.com/numen31337/copy_with_extension/tree/master/copy_with_extension_gen
issue_tracker: https://github.com/numen31337/copy_with_extension/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=2.0.0 <6.0.0"
  build: ^2.0.0
  source_gen: ^1.0.0
  copy_with_extension: ^5.0.0
  meta: ^1.8.0

dev_dependencies:
  equatable: ^2.0.5
  flutter_lints: ^2.0.1
  build_runner: ">=1.11.5 <3.0.0"
  test: ^1.20.1
  source_gen_test: ^1.0.1
