name: copy_with_extension_gen
version: 9.1.1
description: Automatically generating `copyWith` extensions code for classes with `@CopyWith()` annotation.
repository: https://github.com/numen31337/copy_with_extension
homepage: https://github.com/numen31337/copy_with_extension/tree/master/copy_with_extension_gen
issue_tracker: https://github.com/numen31337/copy_with_extension/issues

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: '>7.0.0 <9.0.0'
  build: '>3.0.0 <5.0.0'
  source_gen: '>3.0.0 <5.0.0'
  copy_with_extension: ^9.1.1
  meta: '>1.8.0 <2.0.0'

dev_dependencies:
  equatable: ^2.0.7
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  test: ^1.26.3
  source_gen_test: ^1.3.2
  coverage: ^1.15.0
