name: copy_with_extension_gen
version: 1.1.0
description: Automatically generating `copyWith` extensions code for classes with `@CopyWith()` annotation.
repository: https://github.com/numen31337/copy_with_extension
homepage: https://github.com/numen31337/copy_with_extension/tree/master/copy_with_extension_gen
issue_tracker: https://github.com/numen31337/copy_with_extension/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ">=0.39.0 <1.0.0"
  build: ">=1.0.0 <2.0.0"
  logging: ">=0.0.0 <1.0.0"
  source_gen: ">=0.9.0 <1.0.0"
  copy_with_extension:
    git:
      url: git://github.com/JuanM04/copy_with_extension.git
      path: copy_with_extension
      ref: personal

dev_dependencies:
  build_runner: ">=1.0.0 <2.0.0"
  build_test: "<1.0.0"
  test: "<2.0.0"
