name: copy_with_extension_gen
version: 10.0.1
description: Automatically generating `copyWith` extensions code for classes with `@CopyWith()` annotation.
repository: https://github.com/numen31337/copy_with_extension
homepage: https://github.com/numen31337/copy_with_extension/tree/master/copy_with_extension_gen
issue_tracker: https://github.com/numen31337/copy_with_extension/issues

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^8.4.1
  build: ^4.0.0
  source_gen: ^4.0.1
  copy_with_extension: ^10.0.1
  meta: ^1.16.0

dev_dependencies:
  equatable: ^2.0.7
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  test: ^1.26.3
  source_gen_test: ^1.3.2
  coverage: ^1.15.0
